### ISSUE TITLE
User Story : Create Search Method to Accept User Input Ticker Symbols (Jacob and Adam)

### ISSUE THREAD

**Issue by jstremme** [Fund-nominal/FundNominal#3]

**Comment by JacAlexJohns** [comment]
Create a search feature that takes in a Ticker Symbol from a user
Priority: High
Time: TBD (Approximately 2-3 days)

Update search feature to allow for more flexibility in input to find the desired fund
Priority: Medium
Time: TBD (Approximately 1-2 days)

Have search input be stored in required views as a fund object (to be used with other functions)
Priority: High
Time: < 1 day
