### ISSUE TITLE
User Story: Display Exchanges with Ratings (Involves implementing the algorithm)

### ISSUE THREAD

**Issue by jstremme** [Fund-nominal/FundNominal#4]

**Comment by duyng404** [comment]
The interface should have a button "Compare" to go to the Compare screen, where it shows a list of possible exchanges, is sorted in order from the highest score to the lowest score, where the score is determined by the algorithm calculating the attractiveness of the score.

Task 1: Create a new Activity, hosting a Fragment called Compare Fragment, which contain a recyclerView
Estimate: 1 day

Task 2: Hook up the algorithm with the databases, so it calculates the score for each possible exchanges, and store it in a List
Estimate: 2 days

Task 3: Take the list returned by the algorithm, and display it on the RecyclerView.
Estimate: 2 days
