### ISSUE TITLE
User Story: Allow Editing for List of Funds (Break up into adding and removing funds) (Jacob and Adam)

### ISSUE THREAD

**Issue by jstremme** [Fund-nominal/FundNominal#5]

**Comment by Gregorvich** [comment]
This part of the project will allow users to add or remove funds from their list of funds.

User Story 1: Create a method that will update the view to have a edit and delete button for each fund fragment.
Priority: Low
Time: 1 - 2 days

User Story 2: Create a method that will have an add button and will implement the search method.
Priority: High
Time: 1 - 2 days

User Story 3: Implement the edit method for funds and implement a delete method for funds.
Priority: Medium
Time: 2 - 3 days
