### ISSUE TITLE
User Story: Allow Changes to Fund Weights (Over, Under, Normal)

### ISSUE THREAD

**Issue by jstremme** [Fund-nominal/FundNominal#6]

**Comment by speccaN** [comment]
Change weight of fund
User should be able to change the weight of their funds (Over, Under, Normal)
- Task 1: Create a method that takes a fund object and edit its properties.
  Priority: High
  Time: 1 Day
- Task 2: Create user interface functionality to edit fund properties
  Priority: High
  Time: 1 Day
- Task 3 : Create SQL Script for changing the weight property of a fund and Update the Database with    new properties
  Priority: Medium
  Time: 1 Day
- Task 4 : Update UI with new properties
  Priority: Low
  Time: 1 Day
